# -*- coding: utf-8 -*-
"""Heatmaps Code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SIV1JDeCoYIZU5rQ7EYiQ--Z0UuwkMCy
"""

import geopandas as gpd
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os
!pip install shapely==1.8.5 --quiet

# List files in the working directory to verify paths
print("Files in /content/:", os.listdir("/content/"))

# Define file paths
shapefile_path = "/content/cb_2020_us_county_500k.shp"
crime_data_path = "/content/Combined_Crime_SocioEconomic_Data.xlsx"

# Load Florida county shapefile
florida_gdf = gpd.read_file(shapefile_path)
florida_gdf = florida_gdf[florida_gdf["STATEFP"] == "12"]
florida_gdf = florida_gdf[["NAME", "geometry"]].rename(columns={"NAME": "County"})

# Load combined dataset
df = pd.read_excel(crime_data_path)

# Standardize county names
florida_gdf["County"] = florida_gdf["County"].str.title().str.strip()
df["County"] = df["County"].str.title().str.strip()

# Merge data with geospatial file
merged_gdf = florida_gdf.merge(df, on="County", how="inner")

# --- Plot Housing Units Heatmap ---
fig, ax = plt.subplots(1, 1, figsize=(10, 10))
merged_gdf.plot(column="Housing Units", cmap="Blues", legend=True,
                legend_kwds={"label": "Housing Units by County"}, ax=ax)
merged_gdf.boundary.plot(ax=ax, linewidth=0.5, color="black")

for idx, row in merged_gdf.iterrows():
    ax.text(row.geometry.centroid.x, row.geometry.centroid.y, row["County"],
            fontsize=6, ha='center', color='black')

ax.set_title("Housing Units by County in Florida")
ax.set_xlabel("Longitude")
ax.set_ylabel("Latitude")
plt.tight_layout()

# Save the map
output_path = "/content/florida_housing_units_heatmap.png"
fig.savefig(output_path)
print(f"Saved: {output_path}")